### ISSUE TITLE
Can you please update the bootstrap cdn link to 3.3.7?

### ISSUE THREAD

**Issue by ghost** [lewagon/bootstrap-boilerplate#3]
CSS Link
`<link` rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">`

JavaScript Link
`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>`

**Comment by furkanarabaci** [comment]
I pushed the version update, but since this is 1 year old, doubt he/she will check on it.

**Comment by ghost** [comment]
Alrighty

**Comment by ssaunier** [comment]
Fixed by #4

**Comment by ghost** [comment]
thank you so much
